import { Navigation } from "@/components/navigation/navigation"
import { Providers } from "@/components/navigation/providers"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navigation />
        {children}


        </Providers>
        </body>
    </html>
  )
}
